### ISSUE TITLE
Update glommi version, transitive CVE in aHash dependency

### ISSUE THREAD

**Issue by JBartscher** [waynexia/helixdb#5]
Hey I tried to run helixdb and got an error that a transitive dependency of glommi (aHash) has some issues.
I found this [#163 Issue](https://github.com/tkaitchuck/aHash/issues/163) in the aHash repository. Which is why all versions prior to 0.7.7 are yanked. I couldnt get it to work (I am relativly new to rust) so I am not opening a PR which might break stuff but I would appreaciate it if you could look into the Issue as I realy like the idea of helixdb.

**Comment by waynexia** [comment]
Thanks for reporting! I opened PR #6 to update deps version as well as the rust toolchain. Please check it out!

BTW, I only make sure all existing tests can pass. But I didn't confirm all the logic works the same as under the old version. There may be some implicit changes that I wasn't aware of.

**Comment by waynexia** [comment]
Closed due to the PR is merged. Feel free to reopen it if there is still any problem on your side.
